### ISSUE TITLE
How can I edit the SHAddr file in order to add support to the newest version?

### ISSUE THREAD

**Issue by DavidOldAccount** [C0deH4cker/libstubhook-examples#3]
Seems like there are some hex numbers, can I use IDA or HxD to find the item lists' hex number?
Thx

**Comment by C0deH4cker** [comment]
Those are ASLR-shifted addresses. You need to know how to get these from the application by reverse engineering it. This is a very difficult task if you have never done it before. And yes, generally IDA Pro is used for this task.
